### STAGE 1: Build ###
FROM node:current-alpine3.15
WORKDIR /app

# Ensure clean installation
RUN npm cache clean --force

# Install dependencies
COPY package*.json ./
RUN npm i
COPY . ./

# Application metadata
EXPOSE 4200
CMD ["npm", "run", "build", "--prod"]
