######## STAGE 1: Build
FROM node:18-alpine3.15 as builder
WORKDIR /app

# Ensure clean installation
RUN npm cache clean --force

# Install dependencies
COPY package*.json ./
RUN apk add --update python3 make g++ \
   && rm -rf /var/cache/apk/*
RUN npm i
COPY . ./

RUN npm run build --omit=dev

######## Stage 2: Run
FROM nginx
EXPOSE 80
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/www /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/nginx.conf
