language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f frontend/dely/dockerfiles/Dockerfie.dev -t lvdkleij/deli-app .

script:
  - docker run -e CI=true lvdkleij/deli-app npm run test
