version: "3.9"
services:
  reverse_proxy:
    image: lakleij/app-shopping-list-reverse-proxy
    ports:
      - "80:80"
    networks:
      - nginx_proxy
    depends_on:
      - frontend-app

  frontend-app:
    image: lakleij/app-shopping-list-frontend-app
    expose:
      - "8100"
    networks:
      - backend
      - nginx_proxy
    depends_on:
      - backend-authentication

  backend-authentication:
    image: lakleij/app-shopping-list-backend-user-authentication
    environment:
      - PGUSER=${PG_USER}
      - PGHOST=${PG_HOST}
      - PGDATABASE=${PG_DATABASE}
      - PGPASSWORD=${PG_PASSWORD}
      - PGPORT=${PG_PORT}
    expose:
      - "6300"
    networks:
      - backend


networks:
  nginx_proxy:
    driver: bridge
  backend:
    driver: bridge