FROM node:18-alpine3.15 as builder
WORKDIR /app

RUN npm cache clean --force

COPY package*.json ./
COPY tsconfig.json ./
COPY src ./src

RUN npm i
RUN npm run build --omit=dev

## this is stage two , where the app actually runs
FROM node:18-alpine3.15
WORKDIR /app

RUN npm cache clean --force

COPY package*.json ./

RUN npm i --only=production
COPY --from=builder /app/www .
RUN npm install pm2 -g
CMD ["pm2-runtime","server.js"]