FROM node:18-alpine3.15
WORKDIR /app

# Ensure clean installation
RUN npm cache clean --force

# Install dependencies
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 6300

CMD ["npm", "run", "start"]