### STAGE 1: Build ###
FROM node:18-alpine3.15
WORKDIR /app

# Ensure clean installation
RUN npm cache clean --force

# Install dependencies
COPY package*.json ./
RUN npm i -g @angular/cli
RUN npm i -g @ionic/cli

# ## Install python dependency (not by default in alpine version)
RUN apk add --update python3 make g++ \
   && rm -rf /var/cache/apk/*

RUN npm i

COPY . ./

# Application metadata
EXPOSE 8100
CMD ["npm", "run", "start"]
