version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8100:8100"
    volumes:
      - "/app/node_modules"
      - ".:/app"
    stdin_open: true
    tty: true
