version: '3.8'
services:
  postgres:
    image: postgres:14.5
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      dockerfile: dockerfiles/Dockerfile.dev
      context: .
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 6300:6300
    depends_on:
      postgres:
        condition: service_healthy